on:
  workflow_dispatch:
  schedule:
    - cron: '45 */168 * * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t-3es/te1pl2te@cron
        with:
          token: ${{ secrets.token }}
